name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest instead of windows10 for compatibility
    strategy:
      matrix:
        r-version: ['4.4.1', '4.4.2']  # Matrix for different R versions

    steps:
      - uses: actions/checkout@v4  # Checkout the repository
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2  # Use latest stable version instead of a specific commit
        with:
          r-version: ${{ matrix.r-version }}  # Set the R version from the matrix

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))  # Install remotes and rcmdcheck
          remotes::install_deps(dependencies = TRUE)  # Install all dependencies from DESCRIPTION
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")  # Run rcmdcheck to check the package
        shell: Rscript {0}
